camera:
  source: 1  # 0 for webcam, or IP camera URL
  width: 640
  height: 480
  fps: 60

tracking:
  method: "optical_flow"  # "optical_flow" or "color_tracking"
  sensitivity: 4.0
  smoothing_factor: 0.2

optical_flow:
  max_corners: 100
  quality_level: 0.3
  min_distance: 7
  block_size: 7

color_tracking:
  lower_hsv: [35, 50, 50]
  upper_hsv: [85, 255, 255]

display:
  show_camera: true
  show_desktop: true
  window_width: 800
  window_height: 600
  fps_display: true

cursor:
  movement_mode: "relative"  # "relative" or "absolute"
  boundary_margin: 50


recording:
  enabled: true  # Set to true to record video
  output_file: "optical_mouse_demo_3.mp4"
  show_tracking_canvas: true  # Black canvas with cursor trails
  trail_length: 100  # Number of trail points to keep
  fps: 20  # Recording FPS