"""
Configuration Package
Provides default configuration constants and utilities
"""

from .default_config import *

__all__ = [
    'DEFAULT_CAMERA_SOURCE',
    'DEFAULT_CAMERA_WIDTH',
    'DEFAULT_CAMERA_HEIGHT',
    'DEFAULT_CAMERA_FPS',
    'DEFAULT_TRACKING_METHOD',
    'DEFAULT_SENSITIVITY',
    'DEFAULT_SMOOTHING_FACTOR',
    'DEFAULT_MAX_CORNERS',
    'DEFAULT_QUALITY_LEVEL',
    'DEFAULT_MIN_DISTANCE',
    'DEFAULT_BLOCK_SIZE',
    'DEFAULT_LOWER_HSV',
    'DEFAULT_UPPER_HSV',
    'DEFAULT_SHOW_CAMERA',
    'DEFAULT_SHOW_DESKTOP',
    'DEFAULT_WINDOW_WIDTH',
    'DEFAULT_WINDOW_HEIGHT',
    'DEFAULT_FPS_DISPLAY',
    'DEFAULT_MOVEMENT_MODE',
    'DEFAULT_BOUNDARY_MARGIN',
]
